services:
  - type: worker
    name: kael-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kael_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
